dining_hall/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView

from dining_hall.accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'login/', LoginView.as_view(template_name='accounts/login.html'),
        name='login'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('home/', views.HomeRedirectView.as_view(), name='home'),
    path('student/', views.StudentHomeView.as_view(), name='student'),
    path(
        'add_reservation/', views.AddReservationView.as_view(),
        name='add_reservation'
    ),
    path(
        'cancel_reservation/', views.CancelReservationView.as_view(),
        name='cancel_reservation'
    ),
    path(
        'profile/<str:pk>', views.StudentProfileView.as_view(), name='profile'
    ),
    path('historic/', views.HistoryStudentView.as_view(), name='historic'),
    path('pending/', views.PendingStudentView.as_view(), name='pending'),
    path('servant/', views.ServantHomeView.as_view(), name='servant'),
    path('add_student/', views.AddStudentView.as_view(), name='add_student'),
    path(
        'list_student/', views.ListStudentView.as_view(), name='list_student'
    ),
    path(
        'inative_student/<str:pk>', views.InativeStudentView.as_view(),
        name='inative_student'
    ),
    path(
        'edit_student/<str:pk>', views.UpdateStudentView.as_view(),
        name='edit_student'
    ),
    path('add_servant/', views.AddServantView.as_view(), name='add_servant'),
    path(
        'list_servant/', views.ListServantView.as_view(), name='list_servant'
    ),
    path(
        'inative_servant/<str:pk>', views.InativeServantView.as_view(),
        name='inative_servant'
    ),
    path(
        'edit_servant/<str:pk>', views.UpdateServantView.as_view(),
        name='edit_servant'
    ),
    path('add_food/', views.AddFoodView.as_view(), name='add_food'),
    path('list_food/', views.ListFoodView.as_view(), name='list_food'),
    path(
        'edit_food/<str:pk>', views.UpdateFoodView.as_view(), name='edit_food'
    ),
    path(
        'list_pending/', views.ListPendingView.as_view(), name='list_pending'
    ),
    path(
        'update_pass/', views.UserPasswordChangeView.as_view(),
        name='update_pass'
    ),
    path(
        'remove_pending/<str:pk>', views.RemovePendingView.as_view(),
        name='remove_pending'
    ),
    path(
        'confirm_reservation/', views.ConfirmReservationView.as_view(),
        name='confirm_reservation'
    ),
]

dining_hall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static

from dining_hall import settings
from dining_hall.accounts.views import HomeRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('dining_hall.accounts.urls')),
    path('', HomeRedirectView.as_view(), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Refeitório - IFPI"
admin.site.site_title = "Sistema de Administração do Refeitório - IFPI"
admin.site.index_title = "Refeitório - IFPI"

dining_hall/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from dining_hall.accounts.models import Student, Servant
from dining_hall.food.models import Reservation


class StudantCreateForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Senha', widget=forms.PasswordInput, required=True
    )
    password2 = forms.CharField(
        label='Confirmação de senha', widget=forms.PasswordInput,
        required=True
    )
    username = forms.CharField(label='Matrícula')

    class Meta:
        model = Student
        fields = [
            'username', 'name', 'email', 'entry_date', 'birthdate', 'cpf',
            'rg', 'phone', 'profilepic', 'student_class', 'password1',
            'password2'
        ]

    def clean_password2(self):
        """
        Check IF the password entries match.
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas não são iguais.")
        return password2

    def save(self, commit=True):
        """
        Save the provided password in hashed format
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class AddMotivePendingForm(forms.Form):
    motive = forms.CharField(label='Motivo')


class ConfirmReservationForm(forms.ModelForm):
    username = forms.CharField(label='Matrícula')

    class Meta:
        model = Reservation
        fields = ['username']
    
    def save(self, commit=True):
        reservation = super().save(commit=False)
        reservation.pending=False
        if commit:
            reservation.save()
        return reservation



class ServantCreateForm(UserCreationForm):
    username = forms.CharField(label='SUAP')

    class Meta:
        model = Servant
        fields = [
            'username', 'name', 'email', 'entry_date', 'profilepic', 'campus',
            'password1', 'password2'
        ]


class ServantUpdateForm(UserChangeForm):
    username = forms.CharField(label='SUAP', disabled=True)

    class Meta:
        model = Servant
        fields = [
            'username', 'name', 'email', 'entry_date', 'profilepic', 'campus'
        ]

    def __init__(self, *args, **kwargs):
        super(ServantUpdateForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['name'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields['entry_date'].widget.attrs['readonly'] = True

dining_hall/accounts/views.py
from datetime import datetime
from itertools import chain

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.base import RedirectView, TemplateView, View
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from dining_hall.accounts.forms import (
    StudantCreateForm, ServantCreateForm, ServantUpdateForm,
    ConfirmReservationForm
)
from dining_hall.accounts.mixins import (
    RedirectStudentMixin, RedirectServantMixin
)
from dining_hall.accounts.models import Servant, Student, User
from dining_hall.food.models import Food, Reservation
from dining_hall.food.forms import FoodAddForm, PendingRemoveForm



@method_decorator(login_required, name='dispatch')
class HomeRedirectView(RedirectView):

    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        try: 
            student = Student.objects.get(id=self.request.user.id)
            if student:
                return reverse_lazy('accounts:student')
        except:
            try:
                servant = Servant.objects.get(id=self.request.user.id)
                if servant:
                    return reverse_lazy('accounts:servant')
            except:
                if self.request.user.id:
                    return reverse_lazy('admin:index')
                login_message = 'Ops, faça login para acessar essa página'
                messages.error(self.request, login_message)
                return reverse_lazy('accounts:login')


@method_decorator(login_required, name='dispatch')
class StudentHomeView(RedirectStudentMixin, TemplateView):
    template_name = "accounts/student_home.html"

    def get_context_data(self, **kwargs):
        context = super(StudentHomeView, self).get_context_data(**kwargs)
        context['page_name'] = 'home'
        lim_quant = 'Não disponível'
        total_quant = 'Não disponível'
        reservations = 'Não disponível'
        available = 'Não disponível'
        type_food = ' - fora do horário de reservas'
        try:
            foods = Food.objects.filter(date=datetime.now())
            if datetime.now().hour <= 12:
                food = foods.get(type_food='Almoço')
                context['food'] = food
                lim_quant = food.limit_quantity
                total_quant = food.total_quantity
                if food.limit_quantity < 1:
                    lim_quant = 'Não disponível'
                type_food = ' - Almoço'
                reservations = Reservation.objects.filter(food=food).count()
            if datetime.now().hour >= 18:
                type_food = ' - Jantar'
                food = foods.get(type_food='Jantar')
                context['food'] = food
                lim_quant = food.limit_quantity
                total_quant = food.total_quantity
                if food.limit_quantity < 1:
                    lim_quant = 'Não disponível'
                reservations = Reservation.objects.filter(food=food).count()
                lim_quant = food.total_quant - reservations
        except:
            pass
        if datetime.now().hour > 10 and datetime.now().hour < 14 or \
                datetime.now().hour > 23:
            context['reservation_unavailable'] = True
        context['total_quant'] = total_quant
        context['type_food'] = type_food
        context['reservations'] = reservations
        context['lim_quant'] = lim_quant
        context['available'] = available
        context['peding'] = Reservation.objects.filter(
            registered_user=self.request.user
        ).filter(pending=True).count()
        context["student"] = Student.objects.get(id=self.request.user.id)
        return context


@method_decorator(login_required, name='dispatch')
class AddReservationView(View):

    def get(self, *args, **kwargs):
        foods = Food.objects.filter(date=datetime.now())
        if datetime.now().hour <= 12:
            food = foods.get(type_food='Almoço')
        if datetime.now().hour >= 18:
            food = foods.get(type_food='Jantar')
        student = Student.objects.get(id=self.request.user.id)
        reservations = Reservation.objects.filter(date=datetime.now()).filter(
            registered_user=student).filter(food=food)
        if(len(reservations)) >= 1:
            messages.warning(
                self.request, 'Ops, já existe reserva para essa refeição'
            )
            return redirect(reverse_lazy('accounts:home'))
        reservation = Reservation.objects.create(
            date=datetime.now(), food=food,
            registered_user=student
        )
        food.limit_quantity = food.limit_quantity - 1
        food.save()
        reservation.save()
        messages.success(self.request, 'Reserva feita com sucesso!')
        return redirect(reverse_lazy('accounts:home'))


@method_decorator(login_required, name='dispatch')
class CancelReservationView(View):

    def get(self, *args, **kwargs):
        foods = Food.objects.filter(date=datetime.now())
        if datetime.now().hour <= 12:
            try:
                food = foods.get(type_food='Almoço')
            except Food.DoesNotExist:
                pass
        if datetime.now().hour >= 18:
            try:
                food = foods.get(type_food='Jantar')
            except Food.DoesNotExist:
                pass
        student = Student.objects.get(id=self.request.user.id)
        reservations = Reservation.objects.filter(date=datetime.now()).filter(
            registered_user=student).filter(food=food)
        if(len(reservations)) >= 1:
            messages.success(self.request, 'Reserva cancelada com sucesso')
            reservations[0].delete()
            food.limit_quantity = food.limit_quantity + 1
            food.save()
            return redirect(reverse_lazy('accounts:home'))
        else:
            messages.warning(
                self.request, 'Não há reserva do aluno a ser cancelada'
            )
            return redirect(reverse_lazy('accounts:home'))


@method_decorator(login_required, name='dispatch')
class HistoryStudentView(ListView):
    template_name = "accounts/history_student.html"

    def get_queryset(self):
        queryset = Reservation.objects.filter(
            registered_user__id=self.request.user.id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HistoryStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'history'
        return context


@method_decorator(login_required, name='dispatch')
class PendingStudentView(ListView):
    template_name = "accounts/pending_student.html"

    def get_queryset(self):
        queryset = Reservation.objects.filter(
            registered_user__id=self.request.user.id).filter(pending=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(PendingStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'peding'
        return context


@method_decorator(login_required, name='dispatch')
class StudentProfileView(DetailView):
    model = Student
    template_name = "accounts/student_profile.html"

    def get_context_data(self, **kwargs):
        context = super(StudentProfileView, self).get_context_data(**kwargs)
        context['page_name'] = 'profile'
        return context


@method_decorator(login_required, name='dispatch')
class ServantHomeView(RedirectServantMixin, TemplateView):
    template_name = "accounts/servant_home.html"

    def get_context_data(self, **kwargs):
        context = super(ServantHomeView, self).get_context_data(**kwargs)
        today = datetime.now()
        context['page_name'] = 'home'
        type_food = 'Almoço'
        context['type_food'] = 'Não disponível'
        total_reservations = 0
        reservations = 0
        available = 0
        if today.hour > 12:
            type_food = 'Jantar'
        try:
            foods = Food.objects.filter(date=today)
            if foods.count() >= 1:
                food = foods.get(type_food=type_food)
                total_reservations = food.total_quantity
                reservations = Reservation.objects.filter(food=food).count()
                available = total_reservations - reservations
                context['type_food'] = str(food)
        except:
            pass
        pending = Reservation.objects.filter(pending=True).count()
        context['peding'] = pending
        context['available'] = available
        context['reservations'] = reservations
        context['total_reservations'] = total_reservations
        context['page_name'] = 'home'
        context["servant"] = Servant.objects.get(id=self.request.user.id)
        return context


class AddStudentView(SuccessMessageMixin, CreateView):
    model = Student
    template_name = 'accounts/add_student.html'
    form_class = StudantCreateForm
    success_url = reverse_lazy('accounts:add_student')
    success_message = 'Aluno adicionado com sucesso'

    def get_context_data(self, **kwargs):
        context = super(AddStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'student'
        context['action'] = 'Cadastrar'
        return context


@method_decorator(login_required, name='dispatch')
class ListStudentView(ListView):
    model = Student
    template_name = "accounts/list_student.html"

    def get_queryset(self):
        queryset = Student.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'student'
        return context


@method_decorator(login_required, name='dispatch')

dining_hall/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Painel do Aluno</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
	
	<!--Custom Font-->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand" href="#"><span>Refeitório</span><span style="color: #2b9f3f">IFPI</span></a>
				<ul class="nav navbar-top-links navbar-right">
				</ul>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<div class="profile-sidebar">
			<div class="profile-userpic">
				<img src="{% if  request.user.profilepic %}{{ request.user.profilepic.url }}{% endif %}" class="img-responsive" alt="">

			</div>
			<div class="profile-usertitle">
				<div class="profile-usertitle-name">{{request.user.name}}</div>
				<div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="divider"></div>
		<ul class="nav menu">
			<li class="{% if page_name == 'home' %} active {% endif %}"><a href="{% url 'accounts:home' %}"><em class="fa fa-dashboard">&nbsp;</em> Início</a></li>
			<li class="{% if page_name == 'profile' %} active {% endif %}"><a href="{% url 'accounts:profile' pk=request.user.id %}"><em class="fa fa-user">&nbsp;</em> Perfil</a></li>
			<li class="{% if page_name == 'history' %} active {% endif %}"><a href="{% url 'accounts:historic' %}"><em class="fa fa-calendar">&nbsp;</em> Histórico</a></li>
			<li class="{% if page_name == 'peding' %} active {% endif %}"><a href="{% url 'accounts:pending' %}"><em class="fa fa-warning">&nbsp;</em> Pendências</a></li>
			<li><a href="{% url 'accounts:logout' %}"><em class="fa fa-power-off">&nbsp;</em> Sair</a></li>
		</ul>
    </div>
    {% block content %}{% endblock %}
		<div class="row">
			<div class="col-lg-12">
				<h7>&nbsp;</h7>
			</div>
		</div>
		<div class="row">
			
			<div class="col-sm-12">
				<p class="back-link">Desenvolvido por <a href="https://www.ifpi.edu.br/" target="blank">IFPI</a></p>
			</div>
		</div>
	</div>
	
	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/chart.min.js' %}"></script>
	<script src="{% static 'js/chart-data.js' %}"></script>
	<script src="{% static 'js/easypiechart.js' %}"></script>
	<script src="{% static 'js/easypiechart-data.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script>
		window.onload = function () {
	var chart1 = document.getElementById("line-chart").getContext("2d");
	window.myLine = new Chart(chart1).Line(lineChartData, {
	responsive: true,
	scaleLineColor: "rgba(0,0,0,.2)",
	scaleGridLineColor: "rgba(0,0,0,.05)",
	scaleFontColor: "#c5c7cc"
	});
};
	</script>
		
</body>
</html>

dining_hall/accounts/templates/base_servant.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Painel do Servidor</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
	
	<!--Custom Font-->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand" href="#"><span>Refeitório</span><span style="color: #2b9f3f">IFPI</span></a>
				<ul class="nav navbar-top-links navbar-right">
				</ul>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<div class="profile-sidebar">
			<div class="profile-userpic">
				<img src="{% if  request.user.profilepic %}{{ request.user.profilepic.url }}{% endif %}" class="img-responsive" alt="">
			</div>
			<div class="profile-usertitle">
				<div class="profile-usertitle-name">{{request.user.name}}</div>
				<div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="divider"></div>
		<ul class="nav menu">
			
			<li class="{% if page_name == 'home' %} active {% endif %}">
				<a href="{% url 'accounts:home' %}">
					<em class="fa fa-dashboard">&nbsp;</em> Início
				</a>
			</li>
			<li class="{% if page_name == 'profile' %} active {% endif %}">
				<a href="{% url 'accounts:edit_servant' pk=request.user.id %}">
					<em class="fa fa-user">&nbsp;</em> Perfil
				</a>
			</li>
			<li class="parent {% if page_name == 'student' %} active {% endif %}">
				<a data-toggle="collapse" href="#sub-item-1">
					<em class="fa fa-graduation-cap">&nbsp;</em>	Aluno
					<span data-toggle="collapse" href="#sub-item-1" class="icon pull-right">
						<em class="fa fa-plus"></em>
					</span>
				</a>
				<ul class="children collapse" id="sub-item-1">
					<li>
						<a class="" href="{% url 'accounts:add_student' %}">
							<span class="fa fa-arrow-right"></span>
							Adicionar
						</a>
					</li>
					<li>
						<a class="" href="{% url 'accounts:list_student' %}">
							<span class="fa fa-arrow-right"></span>
							Listar
						</a>
					</li>
				</ul>
			</li>
			<li class="parent {% if page_name == 'servant' %} active {% endif %}">
				<a data-toggle="collapse" href="#sub-item-2">
					<em class="fa fa-user">&nbsp;</em>Servidor
					<span data-toggle="collapse" href="#sub-item-2" class="icon pull-right">
						<em class="fa fa-plus"></em>
					</span>
				</a>
				<ul class="children collapse" id="sub-item-2">
					<li>
						<a class="" href="{% url 'accounts:add_servant' %}">
							<span class="fa fa-arrow-right"></span>
							Adicionar
						</a>
					</li>
					<li>
						<a class="" href="{% url 'accounts:list_servant' %}">
							<span class="fa fa-arrow-right"></span>
							Listar
						</a>
					</li>
				</ul>
			</li>
			<li class="parent ">
				<a data-toggle="collapse" href="#sub-item-3">
					<em class="glyphicon glyphicon-cutlery">&nbsp;</em>Refeição
					<span data-toggle="collapse" href="#sub-item-3" class="icon pull-right">
						<em class="fa fa-plus"></em>
					</span>
				</a>
				<ul class="children collapse" id="sub-item-3">
					<li>
						<a class="" href="{% url 'accounts:add_food' %}">
							<span class="fa fa-arrow-right"></span> Adicionar
						</a>
					</li>
					<li>
						<a class="" href="{% url 'accounts:list_food' %}">
							<span class="fa fa-arrow-right"></span> Listar
						</a>
					</li>
				</ul>
			</li>
			<li class="parent {% if page_name == 'pending' %} active {% endif %}">
				<a href="{% url 'accounts:list_pending' %}"><em class="fa fa-warning">&nbsp;</em> Pendência</a>
			</li>
			<li>
				<a href="{% url 'accounts:confirm_reservation' %}"><i class="fas fa-clock"></i> Hora da refeição</a>
			</li>
			<li>
				<a href="{% url 'accounts:logout' %}"><em class="fa fa-power-off">&nbsp;</em> Sair</a>
			</li>
		</ul>
	</div><!--/.sidebar-->
	{% block content %}
	{% endblock %}
		<div class="row">
			<div class="col-lg-12">
				<h7>&nbsp;</h7>
			</div>
		</div>
		<div class="row">
			
			<div class="col-sm-12">
				<p class="back-link">Desenvolvido por <a href="https://www.ifpi.edu.br/" target="blank">IFPI</a></p>
			</div>
		</div>
	</div>
	
	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/chart.min.js' %}"></script>
	<script src="{% static 'js/chart-data.js' %}"></script>
	<script src="{% static 'js/easypiechart.js' %}"></script>
	<script src="{% static 'js/easypiechart-data.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="https://kit.fontawesome.com/52ff9bea34.js" crossorigin="anonymous"></script>
	<script>
		window.onload = function () {
	var chart1 = document.getElementById("line-chart").getContext("2d");
	window.myLine = new Chart(chart1).Line(lineChartData, {
	responsive: true,
	scaleLineColor: "rgba(0,0,0,.2)",
	scaleGridLineColor: "rgba(0,0,0,.05)",
	scaleFontColor: "#c5c7cc"
	});
};
	</script>
		
</body>
</html>