dining_hall/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView

from dining_hall.accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'login/', LoginView.as_view(template_name='accounts/login.html'),
        name='login'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('home/', views.HomeRedirectView.as_view(), name='home'),
    path('student/', views.StudentHomeView.as_view(), name='student'),
    path(
        'add_reservation/', views.AddReservationView.as_view(),
        name='add_reservation'
    ),
    path(
        'cancel_reservation/', views.CancelReservationView.as_view(),
        name='cancel_reservation'
    ),
    path(
        'profile/<str:pk>', views.StudentProfileView.as_view(), name='profile'
    ),
    path('historic/', views.HistoryStudentView.as_view(), name='historic'),
    path('pending/', views.PendingStudentView.as_view(), name='pending'),
    path('servant/', views.ServantHomeView.as_view(), name='servant'),
    path('add_student/', views.AddStudentView.as_view(), name='add_student'),
    path(
        'list_student/', views.ListStudentView.as_view(), name='list_student'
    ),
    path(
        'inative_student/<str:pk>', views.InativeStudentView.as_view(),
        name='inative_student'
    ),
    path(
        'edit_student/<str:pk>', views.UpdateStudentView.as_view(),
        name='edit_student'
    ),
    path('add_servant/', views.AddServantView.as_view(), name='add_servant'),
    path(
        'list_servant/', views.ListServantView.as_view(), name='list_servant'
    ),
    path(
        'inative_servant/<str:pk>', views.InativeServantView.as_view(),
        name='inative_servant'
    ),
    path(
        'edit_servant/<str:pk>', views.UpdateServantView.as_view(),
        name='edit_servant'
    ),
    path('add_food/', views.AddFoodView.as_view(), name='add_food'),
    path('list_food/', views.ListFoodView.as_view(), name='list_food'),
    path(
        'edit_food/<str:pk>', views.UpdateFoodView.as_view(), name='edit_food'
    ),
    path(
        'list_pending/', views.ListPendingView.as_view(), name='list_pending'
    ),
    path(
        'update_pass/', views.UserPasswordChangeView.as_view(),
        name='update_pass'
    ),
    path(
        'remove_pending/<str:pk>', views.RemovePendingView.as_view(),
        name='remove_pending'
    ),
    path(
        'confirm_reservation/', views.ConfirmReservationView.as_view(),
        name='confirm_reservation'
    ),
]

dining_hall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static

from dining_hall import settings
from dining_hall.accounts.views import HomeRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('dining_hall.accounts.urls')),
    path('', HomeRedirectView.as_view(), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Refeitório - IFPI"
admin.site.site_title = "Sistema de Administração do Refeitório - IFPI"
admin.site.index_title = "Refeitório - IFPI"

dining_hall/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from dining_hall.accounts.models import Student, Servant
from dining_hall.food.models import Reservation


class StudantCreateForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Senha', widget=forms.PasswordInput, required=True
    )
    password2 = forms.CharField(
        label='Confirmação de senha', widget=forms.PasswordInput,
        required=True
    )
    username = forms.CharField(label='Matrícula')

    class Meta:
        model = Student
        fields = [
            'username', 'name', 'email', 'entry_date', 'birthdate', 'cpf',
            'rg', 'phone', 'profilepic', 'student_class', 'password1',
            'password2'
        ]

    def clean_password2(self):
        """
        Check IF the password entries match.
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas não são iguais.")
        return password2

    def save(self, commit=True):
        """
        Save the provided password in hashed format
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class AddMotivePendingForm(forms.Form):
    motive = forms.CharField(label='Motivo')


class ConfirmReservationForm(forms.ModelForm):
    username = forms.CharField(label='Matrícula')

    class Meta:
        model = Reservation
        fields = ['username']
    
    def save(self, commit=True):
        reservation = super().save(commit=False)
        reservation.pending=False
        if commit:
            reservation.save()
        return reservation



class ServantCreateForm(UserCreationForm):
    username = forms.CharField(label='SUAP')

    class Meta:
        model = Servant
        fields = [
            'username', 'name', 'email', 'entry_date', 'profilepic', 'campus',
            'password1', 'password2'
        ]


class ServantUpdateForm(UserChangeForm):
    username = forms.CharField(label='SUAP', disabled=True)

    class Meta:
        model = Servant
        fields = [
            'username', 'name', 'email', 'entry_date', 'profilepic', 'campus'
        ]

    def __init__(self, *args, **kwargs):
        super(ServantUpdateForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['name'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields['entry_date'].widget.attrs['readonly'] = True

dining_hall/accounts/views.py
from datetime import datetime
from itertools import chain

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.base import RedirectView, TemplateView, View
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from dining_hall.accounts.forms import (
    StudantCreateForm, ServantCreateForm, ServantUpdateForm,
    ConfirmReservationForm
)
from dining_hall.accounts.mixins import (
    RedirectStudentMixin, RedirectServantMixin
)
from dining_hall.accounts.models import Servant, Student, User
from dining_hall.food.models import Food, Reservation
from dining_hall.food.forms import FoodAddForm, PendingRemoveForm



@method_decorator(login_required, name='dispatch')
class HomeRedirectView(RedirectView):

    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        try: 
            student = Student.objects.get(id=self.request.user.id)
            if student:
                return reverse_lazy('accounts:student')
        except:
            try:
                servant = Servant.objects.get(id=self.request.user.id)
                if servant:
                    return reverse_lazy('accounts:servant')
            except:
                if self.request.user.id:
                    return reverse_lazy('admin:index')
                login_message = 'Ops, faça login para acessar essa página'
                messages.error(self.request, login_message)
                return reverse_lazy('accounts:login')


@method_decorator(login_required, name='dispatch')
class StudentHomeView(RedirectStudentMixin, TemplateView):
    template_name = "accounts/student_home.html"

    def get_context_data(self, **kwargs):
        context = super(StudentHomeView, self).get_context_data(**kwargs)
        context['page_name'] = 'home'
        lim_quant = 'Não disponível'
        total_quant = 'Não disponível'
        reservations = 'Não disponível'
        available = 'Não disponível'
        type_food = ' - fora do horário de reservas'
        try:
            foods = Food.objects.filter(date=datetime.now())
            if datetime.now().hour <= 12:
                food = foods.get(type_food='Almoço')
                context['food'] = food
                lim_quant = food.limit_quantity
                total_quant = food.total_quantity
                if food.limit_quantity < 1:
                    lim_quant = 'Não disponível'
                type_food = ' - Almoço'
                reservations = Reservation.objects.filter(food=food).count()
            if datetime.now().hour >= 18:
                type_food = ' - Jantar'
                food = foods.get(type_food='Jantar')
                context['food'] = food
                lim_quant = food.limit_quantity
                total_quant = food.total_quantity
                if food.limit_quantity < 1:
                    lim_quant = 'Não disponível'
                reservations = Reservation.objects.filter(food=food).count()
                lim_quant = food.total_quant - reservations
        except:
            pass
        if datetime.now().hour > 10 and datetime.now().hour < 14 or \
                datetime.now().hour > 23:
            context['reservation_unavailable'] = True
        context['total_quant'] = total_quant
        context['type_food'] = type_food
        context['reservations'] = reservations
        context['lim_quant'] = lim_quant
        context['available'] = available
        context['peding'] = Reservation.objects.filter(
            registered_user=self.request.user
        ).filter(pending=True).count()
        context["student"] = Student.objects.get(id=self.request.user.id)
        return context


@method_decorator(login_required, name='dispatch')
class AddReservationView(View):

    def get(self, *args, **kwargs):
        foods = Food.objects.filter(date=datetime.now())
        if datetime.now().hour <= 12:
            food = foods.get(type_food='Almoço')
        if datetime.now().hour >= 18:
            food = foods.get(type_food='Jantar')
        student = Student.objects.get(id=self.request.user.id)
        reservations = Reservation.objects.filter(date=datetime.now()).filter(
            registered_user=student).filter(food=food)
        if(len(reservations)) >= 1:
            messages.warning(
                self.request, 'Ops, já existe reserva para essa refeição'
            )
            return redirect(reverse_lazy('accounts:home'))
        reservation = Reservation.objects.create(
            date=datetime.now(), food=food,
            registered_user=student
        )
        food.limit_quantity = food.limit_quantity - 1
        food.save()
        reservation.save()
        messages.success(self.request, 'Reserva feita com sucesso!')
        return redirect(reverse_lazy('accounts:home'))


@method_decorator(login_required, name='dispatch')
class CancelReservationView(View):

    def get(self, *args, **kwargs):
        foods = Food.objects.filter(date=datetime.now())
        if datetime.now().hour <= 12:
            try:
                food = foods.get(type_food='Almoço')
            except Food.DoesNotExist:
                pass
        if datetime.now().hour >= 18:
            try:
                food = foods.get(type_food='Jantar')
            except Food.DoesNotExist:
                pass
        student = Student.objects.get(id=self.request.user.id)
        reservations = Reservation.objects.filter(date=datetime.now()).filter(
            registered_user=student).filter(food=food)
        if(len(reservations)) >= 1:
            messages.success(self.request, 'Reserva cancelada com sucesso')
            reservations[0].delete()
            food.limit_quantity = food.limit_quantity + 1
            food.save()
            return redirect(reverse_lazy('accounts:home'))
        else:
            messages.warning(
                self.request, 'Não há reserva do aluno a ser cancelada'
            )
            return redirect(reverse_lazy('accounts:home'))


@method_decorator(login_required, name='dispatch')
class HistoryStudentView(ListView):
    template_name = "accounts/history_student.html"

    def get_queryset(self):
        queryset = Reservation.objects.filter(
            registered_user__id=self.request.user.id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HistoryStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'history'
        return context


@method_decorator(login_required, name='dispatch')
class PendingStudentView(ListView):
    template_name = "accounts/pending_student.html"

    def get_queryset(self):
        queryset = Reservation.objects.filter(
            registered_user__id=self.request.user.id).filter(pending=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(PendingStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'peding'
        return context


@method_decorator(login_required, name='dispatch')
class StudentProfileView(DetailView):
    model = Student
    template_name = "accounts/student_profile.html"

    def get_context_data(self, **kwargs):
        context = super(StudentProfileView, self).get_context_data(**kwargs)
        context['page_name'] = 'profile'
        return context


@method_decorator(login_required, name='dispatch')
class ServantHomeView(RedirectServantMixin, TemplateView):
    template_name = "accounts/servant_home.html"

    def get_context_data(self, **kwargs):
        context = super(ServantHomeView, self).get_context_data(**kwargs)
        today = datetime.now()
        context['page_name'] = 'home'
        type_food = 'Almoço'
        context['type_food'] = 'Não disponível'
        total_reservations = 0
        reservations = 0
        available = 0
        if today.hour > 12:
            type_food = 'Jantar'
        try:
            foods = Food.objects.filter(date=today)
            if foods.count() >= 1:
                food = foods.get(type_food=type_food)
                total_reservations = food.total_quantity
                reservations = Reservation.objects.filter(food=food).count()
                available = total_reservations - reservations
                context['type_food'] = str(food)
        except:
            pass
        pending = Reservation.objects.filter(pending=True).count()
        context['peding'] = pending
        context['available'] = available
        context['reservations'] = reservations
        context['total_reservations'] = total_reservations
        context['page_name'] = 'home'
        context["servant"] = Servant.objects.get(id=self.request.user.id)
        return context


class AddStudentView(SuccessMessageMixin, CreateView):
    model = Student
    template_name = 'accounts/add_student.html'
    form_class = StudantCreateForm
    success_url = reverse_lazy('accounts:add_student')
    success_message = 'Aluno adicionado com sucesso'

    def get_context_data(self, **kwargs):
        context = super(AddStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'student'
        context['action'] = 'Cadastrar'
        return context


@method_decorator(login_required, name='dispatch')
class ListStudentView(ListView):
    model = Student
    template_name = "accounts/list_student.html"

    def get_queryset(self):
        queryset = Student.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListStudentView, self).get_context_data(**kwargs)
        context['page_name'] = 'student'
        return context


@method_decorator(login_required, name='dispatch')

dining_hall/accounts/templates/accounts/add_servant.html
{% extends "base_servant.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li>
				<a style="color: #000000;" href="{% url 'accounts:home' %}">
					<em class="fa fa-home"></em>
					Servidor
				</a>
			</li>
			<li class="bread-active">Servidor</li>
			<li class="bread-active">{{action}}</li>
		</ol>
	</div><!--/.row-->
	<br>
	{% if messages %}
		{% for message in messages %}
			<div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-{{ message.tags }} {% endif %}" role="alert">
			{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-lg-12">
			<h7>&nbsp;</h7>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading d-flex justify-content-between">
						<div class="col-md-10">{{action}} Servidor</div>
						{% if page_name == 'profile' %}
						<a class="btn btn-warning ml-auto" href="{% url 'accounts:update_pass' %}">
							<i class="fa fa-edit"></i>&nbsp;Alterar a senha
						</a>
						{% endif%}
					
				</div>					
				<div class="panel-body">
					<form class="form-vertical" action="" method="post" enctype="multipart/form-data" autocomplete="off">
						{% csrf_token %}
						<fieldset>
							<div class="col-md-12">
								<div class="row">
									<div class="col-md-3">
										{{ form.username | bootstrap}}
									</div>
									<div class="col-md-5">
										{{ form.name | bootstrap}}
									</div>
									<div class="col-md-4">
										{{ form.email | bootstrap}}
									</div>
								</div>
								
								<div class="row">
									<div class="col-md-3">
										{{ form.entry_date | bootstrap}}
									</div>
									{% if form.password1 %}
									<div class="col-md-5">
										{{ form.password1 | bootstrap}}
									</div>
									<div class="col-md-4">
										{{ form.password2 | bootstrap}}
									</div>
									
								</div>
								<div class="row">
									{% endif %}
									<div class="col-md-5">
										{{ form.profilepic | bootstrap}}
									</div>
									<div class="col-md-4">
										{{ form.campus | bootstrap}}
									</div>
								</div>
								</div>
									
									<!-- Form actions -->
									<div class="form-group">
										<div class="col-md-12 widget-right">
											<button type="submit" class="btn btn-default btn-md pull-right">Enviar</button>
										</div>
									</div>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock%}

dining_hall/accounts/templates/accounts/list_food.html
{% extends "base_servant.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li>
				<a style="color: #000000;" href="{% url 'accounts:home' %}">
					<em class="fa fa-home"></em>
					Servidor
				</a>
			</li>
			<li class="bread-active">Refeição</li>
			<li class="bread-active">Listar</li>
		</ol>
	</div><!--/.row-->
	<br>
	{% if messages %}
		{% for message in messages %}
			<div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-{{ message.tags }} {% endif %}" role="alert">
			{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-lg-12">
			<h7>&nbsp;</h7>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default ">
				<div class="panel-heading">Refeoões</div>
				<div class="panel-body timeline-container">
					<ul class="timeline">
						{% for food in object_list %}
						<li>
							<div class="timeline-badge primary">
								<em class="glyphicon glyphicon-cutlery"></em>
							</div>
							<div class="timeline-panel">
								<div class="timeline-body">
									<div class="col-md-6">
										<p style="color: #000000;"><b>Descrição: </b>{{ food.description }}</p>
										<p style="color: #000000;"><b>Data: </b>{{ food.date }}</p>										
										<p style="color: #000000;"><b>Servidor que cadastrou: </b>{{ food.registered_user }}</p>										
									</div>
									<div class="col-md-6">
										<p style="color: #000000;"><b>Quantidade limite: </b>{{ food.limit_quantity }}</p>
										<p style="color: #000000;"><b>Tipo de refeição: </b>{{ food.type_food }}</p>
										<a class="btn btn-warning" href="{% url 'accounts:edit_food' pk=food.id %}">
											<em class="glyphicon glyphicon-edit"></em> Alterar</a>
									</div>
								</div>
							</div>
						</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div><!--/.col-->
	</div>
	</div>
{% endblock%}

dining_hall/accounts/templates/accounts/list_student.html
{% extends "base_servant.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li>
				<a style="color: #000000;" href="{% url 'accounts:home' %}">
					<em class="fa fa-home"></em>
					Servidor
				</a>
			</li>
			<li class="bread-active">Aluno</li>
			<li class="bread-active">Listar</li>
		</ol>
	</div><!--/.row-->
	<br>
	{% if messages %}
		{% for message in messages %}
			<div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-{{ message.tags }} {% endif %}" role="alert">
			{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-lg-12">
			<h7>&nbsp;</h7>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default ">
				<div class="panel-heading">Alunos</div>
				<div class="panel-body timeline-container">
					<ul class="timeline">
						{% for student in object_list %}
						<li>
							<div class="timeline-badge primary {% if student.is_active %} success {% endif %}">
								<em class="glyphicon glyphicon-user"></em>
							</div>
							<div class="timeline-panel">
								<div class="timeline-body">
									<div class="col-md-4">
										<p style="color: #000000;"><b>Matrícula: </b>{{ student.username }}</p>
										<p style="color: #000000;"><b>E-mail: </b>{{ student.email }}</p>
										<p style="color: #000000;"><b>Data de Nasc.: </b>{{ student.birthdate }}</p>
										<p style="color: #000000;"><b>RG: </b>{{ student.rg }}</p>
										<p style="color: #000000;"><b>Data de Ingresso: </b>{{ student.entry_date }}</p>
										{% if student.is_active %}
										<a class="btn btn-danger" href="{% url 'accounts:inative_student' pk=student.id %}">
											<em class="glyphicon glyphicon-trash"></em> Desativar
										</a>
										{% else %}
										<a class="btn btn-success" href="{% url 'accounts:inative_student' pk=student.id %}">
											<em class="glyphicon glyphicon-check"></em> Ativar
										</a>
										{% endif%}
									</div>
									<div class="col-md-5">
										<p style="color: #000000;"><b>Nome: </b>{{ student.name }}</p>
										<p style="color: #000000;"><b>Telefone: </b>{{ student.phone }}</p>
										<p style="color: #000000;"><b>CPF: </b>{{ student.cpf }}</p>
										<p style="color: #000000;"><b>Turma: </b>{{ student.student_class }}</p>
										<a class="btn btn-warning" href="{% url 'accounts:edit_student' pk=student.id %}">
											<em class="glyphicon glyphicon-edit"></em> Alterar</a>
									</div>
									<div class="col-md-3">
										{% if student.profilepic %}
											<img src="{{ student.profilepic.url }}" class="img-thumbnail " alt="Profilepic" width="200" height="200">
										{% endif %}
									</div>
								</div>
							</div>
						</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div><!--/.col-->
	</div>
	</div>
{% endblock%}

dining_hall/accounts/templates/accounts/reservations.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Refeitório - Reservas</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">Realizar refeição</div>
				<div class="panel-body">
					{% if messages %}
						{% for message in messages %}
							<div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-{{ message.tags }} {% endif %}" role="alert">
							{{ message }}
							</div>
						{% endfor %}
					{% endif %}
					<form role="form" action="." method="POST" autocomplete="off">
						{% csrf_token %}
						<fieldset>
							<div class="col-lg-12">
								<label>Matrícula</label>
								<div class=" ">
									<input type="text" name='username' placeholder="Matrícula" class="form-control">
								</div>
							</div>
							<br>
							<div class="col-lg-12">&nbsp;</div>
							<div class="col-lg-12">
								<center><button class="btn btn-primary">Entrar</button></center>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>	
</body>
</html>

dining_hall/accounts/templates/accounts/student_home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
		
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li>
				<a style="color: #000000;" href="{% url 'accounts:home' %}">
					<em class="fa fa-home"></em>
					Estudante
				</a>
			</li>
		</ol>
	</div><!--/.row-->
	<br>
	{% if messages %}
		{% for message in messages %}
			<div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-{{ message.tags }} {% endif %}" role="alert">
			{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-lg-12">
			<h7>&nbsp;</h7>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default ">
				<div class="panel-heading">Refeição {{ type_food }}</div>
				<div class="panel-body timeline-container">
					<ul class="timeline">
						<li>
							<div class="timeline-badge primary">
								<em class="glyphicon glyphicon-cutlery"></em>
							</div>
							<div class="timeline-panel">
								<div class="timeline-body">
									<p>{{ food }}</p>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div><!--/.col-->
	</div>
	<div class="row">
		<div class="col-md-12">
			
			<div class="col-md-5">
				<center>
					<a href="{% url 'accounts:add_reservation' %}" class="btn btn-lg btn-info {% if lim_quant == 'Não disponível' or reservation_unavailable %} disabled {% endif %}">Reservar refeição</a>
		
				</center>
			</div>
			<div class="col-md-2">&nbsp;</div>
			<div class="col-md-5">
				<center>
					<a href="{% url 'accounts:cancel_reservation' %}" class="btn btn-lg btn-danger {% if lim_quant == 'Não disponível' or reservation_unavailable %} disabled {% endif %}">Cancelar refeição</a>
				</center>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<h7>&nbsp;</h7>
		</div>
	</div>
	<div class="panel panel-container">
		<div class="row">
			<div class="col-xs-6 col-md-3 col-lg-3 no-padding">
				<div class="panel panel-teal panel-widget border-right">
					<div class="row no-padding"><em class="fa fa-xl fa-check-square color-green"></em>
						<div class="{% if total_quant == 'Não disponível' %} h4 {% else %}large{% endif %}">{{ total_quant }}</div>
						<div class="text-muted">Total de reservas</div>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-md-3 col-lg-3 no-padding">
				<div class="panel panel-blue panel-widget border-right">
					<div class="row no-padding"><em class="fa fa-xl fa-exclamation color-orange"></em>
						<div class="{% if reservations == 'Não disponível' %} h4 {% else %}large{% endif %}">{{ reservations }}</div>
						<div class="text-muted">Reservas feitas</div>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-md-3 col-lg-3 no-padding">
				<div class="panel panel-orange panel-widget border-right">
					<div class="row no-padding"><em class="fa fa-xl fa-check color-teal"></em>
						<div class="{% if lim_quant == 'Não disponível' %} h4 {% else %}large{% endif %}">{{ lim_quant }}</div>
						<div class="text-muted">Reservas disponíveis</div>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-md-3 col-lg-3 no-padding">
				<div class="panel panel-red panel-widget ">
					<div class="row no-padding"><em class="fa fa-xl fa-warning color-red"></em>
						<div class="large">{{ peding }}</div>
						<div class="text-muted">Pendências</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
	</div>
{% endblock%}